name: Docker and Push Image in Package
on: workflow_call:

env:
  IMAGEN_TAG: ${{ github.ref_name }}

jobs:
  env-vars:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ env.IMAGEN_TAG }}
    steps:
    - uses: actions/checkout@v4
    - name: add env variables
      shell: bash
      run: |
          echo "IMAGE_TAG=${{ env.IMAGEN_TAG }}" 
  call-workflow-passing-data:
    needs: [env-vars]
    uses: ES-MEV-APPLICATIONS/IssuesExternalRepo/.github/workflows/DockerToPackage.yml@main
    with:
      imagen: es-mev-applications/eoc/deocsso-cnt
      imagen_tag: ${{  needs.env-vars.outputs.IMAGE_TAG }}
    secrets:
      token: "${{ secrets.TOKEN_PACKAGES }}"
